name: Publish to github pages

on: push

jobs:
  deploy:
    steps:
      - name: publish github pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          keep_files: true
